# Generated by Django 6.0.5 on 2026-05-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_seed_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio/', verbose_name='Аудиофайл'),
        ),
    ]
